name: Publish Container

on:
  push:
    branches:
      - main
      - s6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      ### Build and push docker image
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: "fluencelabs/node:latest,fluencelabs/node:${{github.run_number}}"
