name: Publish Container

on:
  workflow_dispatch:
    inputs:
      container_tag:
        description: "Container tag"
        required: false
        default: "latest"
      update_fluence:
        description: Whether to update fluence.json
        required: false
        default: "false"
      version:
        description: 'Fluence version'
        required: false
      url:
        description: 'Fluence binary URL'
        required: false
      sha256:
        description: 'Fluence binary SHA256 hash'
        required: false

jobs:
  build-publish:
    name: Build and publish ${{ github.event.inputs.container_tag || 'latest' }}
    runs-on: ubuntu-latest
    env:
      CONTAINER_TAG: ${{ github.event.inputs.container_tag || 'latest' }}
      UPDATE_FLUENCE: ${{ github.event.inputs.update_fluence == 'true' || github.event.inputs.container_tag == ''  }}
      
    steps:
      - uses: actions/checkout@v2

      - name: Update Fluence in fluence.json to ${{ github.event.inputs.version }}
        if: ${{ env.UPDATE_FLUENCE }}
        run: |
          echo '
          {
            "version": "${{ github.event.inputs.version }}",
            "url": "${{ github.event.inputs.url }}",
            "sha256": "${{ github.event.inputs.sha256 }}"
          }
          ' > fluence/fluence.json

      ### Prepare docker & login to Dockerhub
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine container tags
        run: |
          TAG="${{ env.CONTAINER_TAG }}"
          RUN="${{ github.run_number }}"
          TAGS=fluencelabs/node:${TAG},fluencelabs/node:${TAG}_v${RUN}
          
          echo "TAGS=$TAGS" | tee -a $GITHUB_ENV
          echo "BUILD_DATE=$(date '+%Y-%m-%dT%H:%M:%S%:z')"

      ### Build and push docker image
      - name: Build and push ${{ env.TAGS }}
        id: docker_publish
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: "${{ env.TAGS }}"
          build-args: |
            COMMIT=${{ github.sha }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            RUN_NUMBER=${{ github.run_number }}
            TAG=${{ env.CONTAINER_TAG }}
